DROP TABLE IF EXISTS users1;
CREATE TABLE users1 (
  id INT PRIMARY KEY AUTO_INCREMENT, 
  username VARCHAR(50), 
  pwd VARCHAR(32), 
  age INT,
  is_delete INT NOT NULL DEFAULT 0,
  create_time TIMESTAMP NOT NULL,
  update_time TIMESTAMP NOT NULL);